import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Table, FileText, Link2, Loader2, ClipboardList } from 'lucide-react';
import Papa from 'papaparse';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import type {
  EnsemblGeneData,
  ClinVarVariant,
  GnomADVariant,
  UniProtData,
  ResponseMetadata,
} from '../../lib/api';
import AnimatedButton from '../ui/AnimatedButton';
import ClinicalReportModal from './ClinicalReportModal';

interface ExportToolbarProps {
  gene: EnsemblGeneData;
  clinvarVariants: ClinVarVariant[];
  gnomadVariants: GnomADVariant[];
  protein: UniProtData | null;
  metadata: ResponseMetadata;
  /** Filtered variant IDs from the table (respects active filters) */
  filteredVariantIds: string[] | null;
  onToast: (type: 'success' | 'error' | 'info', message: string) => void;
}

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}

export default function ExportToolbar({
  gene,
  clinvarVariants,
  gnomadVariants,
  protein,
  metadata,
  filteredVariantIds,
  onToast,
}: ExportToolbarProps) {
  const [pdfProgress, setPdfProgress] = useState<{ current: number; total: number } | null>(null);
  const [showReportModal, setShowReportModal] = useState(false);

  // ── CSV Export ──
  const handleExportCsv = useCallback(() => {
    const gnomadMap = new Map(gnomadVariants.map(gv => [gv.variant_id, gv]));

    // Use filtered set if available, otherwise all ClinVar variants
    const variantsToExport = filteredVariantIds
      ? clinvarVariants.filter(cv => filteredVariantIds.includes(cv.variant_id))
      : clinvarVariants;

    const rows = variantsToExport.map(cv => {
      const gv = gnomadMap.get(cv.variant_id);
      return {
        'Variant ID': cv.variant_id,
        'Position': gv?.position || '',
        'Consequence': gv?.consequence || cv.variant_type,
        'Clinical Significance': cv.clinical_significance,
        'Allele Frequency': gv?.allele_frequency || '',
        'Population Frequencies': gv?.population_frequencies
          ?.map(pf => `${pf.population}:${pf.af.toExponential(2)}`)
          .join('; ') || '',
        'Condition': cv.condition,
        'HGVS Coding': gv?.hgvsc || '',
        'HGVS Protein': gv?.hgvsp || '',
        'Review Status': cv.review_status,
        'Variant Type': cv.variant_type,
      };
    });

    const csv = Papa.unparse(rows);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${gene.gene_symbol}_variants_${formatDate()}.csv`;
    link.click();
    URL.revokeObjectURL(url);

    onToast('success', `Exported ${rows.length} variants to CSV`);
  }, [gene.gene_symbol, clinvarVariants, gnomadVariants, filteredVariantIds, onToast]);

  // ── PDF Export ──
  const handleExportPdf = useCallback(async () => {
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;

    const sectionIds = [
      'export-gene-overview',
      'export-protein-info',
      'export-variant-map',
      'export-variant-analytics',
      'export-variant-table',
      'export-disease-associations',
      'export-publications',
    ];

    const availableSections = sectionIds.filter(id => document.getElementById(id));
    const totalPages = availableSections.length + 1; // +1 for cover
    setPdfProgress({ current: 0, total: totalPages });

    const addFooter = (pageNum: number) => {
      pdf.setFontSize(7);
      pdf.setTextColor(120, 130, 150);
      pdf.text(
        `Generated by GeneXplor | ${formatDate()} | Data may be cached`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' },
      );
      pdf.text(`${pageNum}`, pageWidth - margin, pageHeight - 8, { align: 'right' });
    };

    // ── Cover page ──
    pdf.setFillColor(255, 255, 255);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');

    // Logo text
    pdf.setFontSize(12);
    pdf.setTextColor(27, 73, 101);
    pdf.text('GeneXplor', pageWidth / 2, 40, { align: 'center' });

    // Gene symbol
    pdf.setFontSize(48);
    pdf.setTextColor(27, 73, 101);
    pdf.text(gene.gene_symbol, pageWidth / 2, 80, { align: 'center' });

    // Gene name
    pdf.setFontSize(14);
    pdf.setTextColor(30, 41, 59);
    const geneName = gene.gene_name || gene.description;
    const nameLines = pdf.splitTextToSize(geneName, contentWidth);
    pdf.text(nameLines, pageWidth / 2, 95, { align: 'center' });

    // Report title
    pdf.setFontSize(18);
    pdf.setTextColor(100, 116, 139);
    pdf.text('Gene Dashboard Report', pageWidth / 2, 120, { align: 'center' });

    // Date
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth / 2, 135, { align: 'center' });

    // Coordinates
    pdf.setFontSize(9);
    pdf.text(`chr${gene.chromosome}:${gene.start.toLocaleString()}-${gene.end.toLocaleString()} | ${gene.biotype}`, pageWidth / 2, 145, { align: 'center' });

    // Data sources
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.text('Data Sources', pageWidth / 2, 170, { align: 'center' });

    const sources = Object.entries(metadata.data_sources);
    pdf.setFontSize(8);
    sources.forEach(([source, ok], i) => {
      pdf.setTextColor(ok ? 43 : 150, ok ? 159 : 80, ok ? 120 : 80);
      pdf.text(
        `${ok ? '\u2713' : '\u2717'} ${source.charAt(0).toUpperCase() + source.slice(1)}`,
        pageWidth / 2,
        180 + i * 6,
        { align: 'center' },
      );
    });

    addFooter(1);
    setPdfProgress({ current: 1, total: totalPages });

    // ── Content pages ──
    for (let i = 0; i < availableSections.length; i++) {
      const el = document.getElementById(availableSections[i]);
      if (!el) continue;

      pdf.addPage();
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');

      try {
        const canvas = await html2canvas(el, {
          backgroundColor: '#ffffff',
          scale: 2,
          useCORS: true,
          logging: false,
        });

        const imgData = canvas.toDataURL('image/png');
        const imgWidth = contentWidth;
        const imgHeight = (canvas.height / canvas.width) * imgWidth;
        const maxImgHeight = pageHeight - margin * 2 - 15;
        const finalHeight = Math.min(imgHeight, maxImgHeight);
        const finalWidth = imgHeight > maxImgHeight
          ? (canvas.width / canvas.height) * finalHeight
          : imgWidth;

        pdf.addImage(imgData, 'PNG', margin, margin, finalWidth, finalHeight);
      } catch {
        pdf.setFontSize(10);
        pdf.setTextColor(150, 80, 80);
        pdf.text('Section could not be captured', pageWidth / 2, pageHeight / 2, { align: 'center' });
      }

      addFooter(i + 2);
      setPdfProgress({ current: i + 2, total: totalPages });
    }

    pdf.save(`${gene.gene_symbol}_report_${formatDate()}.pdf`);
    setPdfProgress(null);
    onToast('success', `PDF report generated (${totalPages} pages)`);
  }, [gene, metadata, onToast]);

  // ── Share Link ──
  const handleShareLink = useCallback(async () => {
    const url = window.location.href;
    try {
      await navigator.clipboard.writeText(url);
      onToast('success', 'Link copied to clipboard!');
    } catch {
      // Fallback for older browsers
      const input = document.createElement('input');
      input.value = url;
      document.body.appendChild(input);
      input.select();
      document.execCommand('copy');
      document.body.removeChild(input);
      onToast('success', 'Link copied to clipboard!');
    }
  }, [onToast]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: 0.1 }}
      className="flex flex-wrap items-center gap-2 mb-6"
    >
      <AnimatedButton variant="ghost" onClick={handleExportCsv}>
        <span className="flex items-center gap-1.5 text-xs">
          <Table className="w-3.5 h-3.5" />
          Export CSV
        </span>
      </AnimatedButton>

      <AnimatedButton
        variant="ghost"
        onClick={handleExportPdf}
        disabled={!!pdfProgress}
      >
        <span className="flex items-center gap-1.5 text-xs">
          {pdfProgress ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : (
            <FileText className="w-3.5 h-3.5" />
          )}
          {pdfProgress
            ? `Generating PDF... (${pdfProgress.current}/${pdfProgress.total})`
            : 'Export PDF'}
        </span>
      </AnimatedButton>

      <AnimatedButton variant="ghost" onClick={handleShareLink}>
        <span className="flex items-center gap-1.5 text-xs">
          <Link2 className="w-3.5 h-3.5" />
          Share Link
        </span>
      </AnimatedButton>

      <AnimatedButton variant="ghost" onClick={() => setShowReportModal(true)}>
        <span className="flex items-center gap-1.5 text-xs">
          <ClipboardList className="w-3.5 h-3.5" />
          Clinical Report
        </span>
      </AnimatedButton>

      {/* PDF progress bar */}
      <AnimatePresence>
        {pdfProgress && (
          <motion.div
            initial={{ opacity: 0, width: 0 }}
            animate={{ opacity: 1, width: 120 }}
            exit={{ opacity: 0, width: 0 }}
            className="h-1 rounded-full bg-ocean-100 overflow-hidden ml-2"
          >
            <motion.div
              className="h-full bg-primary rounded-full"
              initial={{ width: '0%' }}
              animate={{
                width: `${(pdfProgress.current / pdfProgress.total) * 100}%`,
              }}
              transition={{ duration: 0.3 }}
            />
          </motion.div>
        )}
      </AnimatePresence>
      {/* Clinical Report Modal */}
      <ClinicalReportModal
        isOpen={showReportModal}
        onClose={() => setShowReportModal(false)}
        geneSymbol={gene.gene_symbol}
        onToast={onToast}
      />
    </motion.div>
  );
}
